# taken from https://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html
data_type_map = {
    'AE': 'Application Entity',
    'AS': 'Age String',
    'AT': 'Attribute Tag',
    'CS': 'Code String',
    'DA': 'Date',
    'DS': 'Decimal String',
    'DT': 'Date Time',
    'FL': 'Floating Point Single',
    'FD': 'Floating Point Double',
    'IS': 'Integer String',
    'LO': 'Long String',
    'LT': 'Long Text',
    'OB': 'Other Byte String',
    'OD': 'Other Double String',
    'OF': 'Other Float String',
    'OW': 'Other Word String',
    'PN': 'Person Name',
    'SH': 'Short String',
    'SL': 'Signed Long',
    'SQ': 'Sequence of Items',
    'SS': 'Signed Short',
    'ST': 'Short Text',
    'TM': 'Time',
    'UI': 'Unique Identifier',
    'UL': 'Unsigned Long',
    'UN': 'Unknown',
    'US': 'Unsigned Short',
    'UT': 'Unlimited Text'
}